---
apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "alerts.nais.io"
spec:
  group: "nais.io"
  version: "v1alpha1"
  scope: "Cluster"
  names:
    plural: "alerts"
    singular: "alert"
    kind: "Alert"
    shortNames:
      - al
  additionalPrinterColumns:
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
    - name: Team
      type: string
      JSONPath: .metadata.labels.team
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          required:
            - labels
          properties:
            labels:
              required:
                - team
              properties:
                team:
                  type: string
        spec:
          required:
            - receivers
            - alerts
          properties:
            receivers:
              properties:
                slack:
                  properties:
                    channel:
                      type: string
                    prependText:
                      type: string
                email:
                  properties:
                    to:
                      type: string
                    send_resolve:
                      type: boolean
            alerts:
              type: array
              required:
                - for
                - expr
                - description
              properties:
                description:
                  type: string
                expr:
                  type: string
                for:
                  type: string
                  pattern: '\d+[mh]'
                action:
                  type: string
                documentation:
                  type: string
                sla:
                  type: string
                severity:
                  type: string
